#!/usr/bin/env python
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.8 (standalone edition) on Thu Jan 30 22:10:27 2014
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ESOP(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ESOP.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("button_1"))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ESOP.__set_properties
        self.SetTitle(_("esop1"))
        self.SetSize((512, 300))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ESOP.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.button_1, 0, wx.RIGHT, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class ESOP
class Esop(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        esopFrame = ESOP(None, wx.ID_ANY, "")
        self.SetTopWindow(esopFrame)
        esopFrame.Show()
        return 1

# end of class Esop

if __name__ == "__main__":
    gettext.install("esop") # replace with the appropriate catalog name

    esop = Esop(0)
    esop.MainLoop()